export default {
	login: "devaneyj3",
	id: 25648641,
	node_id: "MDQ6VXNlcjI1NjQ4NjQx",
	avatar_url: "https://avatars.githubusercontent.com/u/25648641?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/devaneyj3",
	html_url: "https://github.com/devaneyj3",
	followers_url: "https://api.github.com/users/devaneyj3/followers",
	following_url:
		"https://api.github.com/users/devaneyj3/following{/other_user}",
	gists_url: "https://api.github.com/users/devaneyj3/gists{/gist_id}",
	starred_url: "https://api.github.com/users/devaneyj3/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/devaneyj3/subscriptions",
	organizations_url: "https://api.github.com/users/devaneyj3/orgs",
	repos_url: "https://api.github.com/users/devaneyj3/repos",
	events_url: "https://api.github.com/users/devaneyj3/events{/privacy}",
	received_events_url: "https://api.github.com/users/devaneyj3/received_events",
	type: "User",
	site_admin: false,
	name: "Jordan Devaney",
	company: null,
	blog: "https://jordandportfolio.netlify.app/portfolio",
	location: null,
	email: null,
	hireable: true,
	bio: "I am currently enrolled in Lambda School taking classes to further my career in Full Stack Web Development.",
	twitter_username: null,
	public_repos: 84,
	public_gists: 1,
	followers: 14,
	following: 15,
	created_at: "2017-02-08T22:07:27Z",
	updated_at: "2021-12-19T22:31:06Z",
};
