export default [
	{
		login: "iandesj",
		id: 2693790,
		node_id: "MDQ6VXNlcjI2OTM3OTA=",
		avatar_url: "https://avatars.githubusercontent.com/u/2693790?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/iandesj",
		html_url: "https://github.com/iandesj",
		followers_url: "https://api.github.com/users/iandesj/followers",
		following_url:
			"https://api.github.com/users/iandesj/following{/other_user}",
		gists_url: "https://api.github.com/users/iandesj/gists{/gist_id}",
		starred_url: "https://api.github.com/users/iandesj/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/iandesj/subscriptions",
		organizations_url: "https://api.github.com/users/iandesj/orgs",
		repos_url: "https://api.github.com/users/iandesj/repos",
		events_url: "https://api.github.com/users/iandesj/events{/privacy}",
		received_events_url: "https://api.github.com/users/iandesj/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "jbarrieault",
		id: 5838323,
		node_id: "MDQ6VXNlcjU4MzgzMjM=",
		avatar_url: "https://avatars.githubusercontent.com/u/5838323?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/jbarrieault",
		html_url: "https://github.com/jbarrieault",
		followers_url: "https://api.github.com/users/jbarrieault/followers",
		following_url:
			"https://api.github.com/users/jbarrieault/following{/other_user}",
		gists_url: "https://api.github.com/users/jbarrieault/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/jbarrieault/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/jbarrieault/subscriptions",
		organizations_url: "https://api.github.com/users/jbarrieault/orgs",
		repos_url: "https://api.github.com/users/jbarrieault/repos",
		events_url: "https://api.github.com/users/jbarrieault/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/jbarrieault/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "IsaiahFlax",
		id: 16263859,
		node_id: "MDQ6VXNlcjE2MjYzODU5",
		avatar_url: "https://avatars.githubusercontent.com/u/16263859?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/IsaiahFlax",
		html_url: "https://github.com/IsaiahFlax",
		followers_url: "https://api.github.com/users/IsaiahFlax/followers",
		following_url:
			"https://api.github.com/users/IsaiahFlax/following{/other_user}",
		gists_url: "https://api.github.com/users/IsaiahFlax/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/IsaiahFlax/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/IsaiahFlax/subscriptions",
		organizations_url: "https://api.github.com/users/IsaiahFlax/orgs",
		repos_url: "https://api.github.com/users/IsaiahFlax/repos",
		events_url: "https://api.github.com/users/IsaiahFlax/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/IsaiahFlax/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "Catherinesjkim",
		id: 17114008,
		node_id: "MDQ6VXNlcjE3MTE0MDA4",
		avatar_url: "https://avatars.githubusercontent.com/u/17114008?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/Catherinesjkim",
		html_url: "https://github.com/Catherinesjkim",
		followers_url: "https://api.github.com/users/Catherinesjkim/followers",
		following_url:
			"https://api.github.com/users/Catherinesjkim/following{/other_user}",
		gists_url: "https://api.github.com/users/Catherinesjkim/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/Catherinesjkim/starred{/owner}{/repo}",
		subscriptions_url:
			"https://api.github.com/users/Catherinesjkim/subscriptions",
		organizations_url: "https://api.github.com/users/Catherinesjkim/orgs",
		repos_url: "https://api.github.com/users/Catherinesjkim/repos",
		events_url: "https://api.github.com/users/Catherinesjkim/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/Catherinesjkim/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "anirban86",
		id: 19902117,
		node_id: "MDQ6VXNlcjE5OTAyMTE3",
		avatar_url: "https://avatars.githubusercontent.com/u/19902117?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/anirban86",
		html_url: "https://github.com/anirban86",
		followers_url: "https://api.github.com/users/anirban86/followers",
		following_url:
			"https://api.github.com/users/anirban86/following{/other_user}",
		gists_url: "https://api.github.com/users/anirban86/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/anirban86/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/anirban86/subscriptions",
		organizations_url: "https://api.github.com/users/anirban86/orgs",
		repos_url: "https://api.github.com/users/anirban86/repos",
		events_url: "https://api.github.com/users/anirban86/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/anirban86/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "shinabarger",
		id: 20525068,
		node_id: "MDQ6VXNlcjIwNTI1MDY4",
		avatar_url: "https://avatars.githubusercontent.com/u/20525068?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/shinabarger",
		html_url: "https://github.com/shinabarger",
		followers_url: "https://api.github.com/users/shinabarger/followers",
		following_url:
			"https://api.github.com/users/shinabarger/following{/other_user}",
		gists_url: "https://api.github.com/users/shinabarger/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/shinabarger/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/shinabarger/subscriptions",
		organizations_url: "https://api.github.com/users/shinabarger/orgs",
		repos_url: "https://api.github.com/users/shinabarger/repos",
		events_url: "https://api.github.com/users/shinabarger/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/shinabarger/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "Dreadrot",
		id: 20604468,
		node_id: "MDQ6VXNlcjIwNjA0NDY4",
		avatar_url: "https://avatars.githubusercontent.com/u/20604468?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/Dreadrot",
		html_url: "https://github.com/Dreadrot",
		followers_url: "https://api.github.com/users/Dreadrot/followers",
		following_url:
			"https://api.github.com/users/Dreadrot/following{/other_user}",
		gists_url: "https://api.github.com/users/Dreadrot/gists{/gist_id}",
		starred_url: "https://api.github.com/users/Dreadrot/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/Dreadrot/subscriptions",
		organizations_url: "https://api.github.com/users/Dreadrot/orgs",
		repos_url: "https://api.github.com/users/Dreadrot/repos",
		events_url: "https://api.github.com/users/Dreadrot/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/Dreadrot/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "shillwil",
		id: 32444141,
		node_id: "MDQ6VXNlcjMyNDQ0MTQx",
		avatar_url: "https://avatars.githubusercontent.com/u/32444141?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/shillwil",
		html_url: "https://github.com/shillwil",
		followers_url: "https://api.github.com/users/shillwil/followers",
		following_url:
			"https://api.github.com/users/shillwil/following{/other_user}",
		gists_url: "https://api.github.com/users/shillwil/gists{/gist_id}",
		starred_url: "https://api.github.com/users/shillwil/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/shillwil/subscriptions",
		organizations_url: "https://api.github.com/users/shillwil/orgs",
		repos_url: "https://api.github.com/users/shillwil/repos",
		events_url: "https://api.github.com/users/shillwil/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/shillwil/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "peterevilla",
		id: 47826392,
		node_id: "MDQ6VXNlcjQ3ODI2Mzky",
		avatar_url: "https://avatars.githubusercontent.com/u/47826392?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/peterevilla",
		html_url: "https://github.com/peterevilla",
		followers_url: "https://api.github.com/users/peterevilla/followers",
		following_url:
			"https://api.github.com/users/peterevilla/following{/other_user}",
		gists_url: "https://api.github.com/users/peterevilla/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/peterevilla/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/peterevilla/subscriptions",
		organizations_url: "https://api.github.com/users/peterevilla/orgs",
		repos_url: "https://api.github.com/users/peterevilla/repos",
		events_url: "https://api.github.com/users/peterevilla/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/peterevilla/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "CyrusTheCurator",
		id: 49468554,
		node_id: "MDQ6VXNlcjQ5NDY4NTU0",
		avatar_url: "https://avatars.githubusercontent.com/u/49468554?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/CyrusTheCurator",
		html_url: "https://github.com/CyrusTheCurator",
		followers_url: "https://api.github.com/users/CyrusTheCurator/followers",
		following_url:
			"https://api.github.com/users/CyrusTheCurator/following{/other_user}",
		gists_url: "https://api.github.com/users/CyrusTheCurator/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/CyrusTheCurator/starred{/owner}{/repo}",
		subscriptions_url:
			"https://api.github.com/users/CyrusTheCurator/subscriptions",
		organizations_url: "https://api.github.com/users/CyrusTheCurator/orgs",
		repos_url: "https://api.github.com/users/CyrusTheCurator/repos",
		events_url: "https://api.github.com/users/CyrusTheCurator/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/CyrusTheCurator/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "karapeoples",
		id: 52808542,
		node_id: "MDQ6VXNlcjUyODA4NTQy",
		avatar_url: "https://avatars.githubusercontent.com/u/52808542?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/karapeoples",
		html_url: "https://github.com/karapeoples",
		followers_url: "https://api.github.com/users/karapeoples/followers",
		following_url:
			"https://api.github.com/users/karapeoples/following{/other_user}",
		gists_url: "https://api.github.com/users/karapeoples/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/karapeoples/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/karapeoples/subscriptions",
		organizations_url: "https://api.github.com/users/karapeoples/orgs",
		repos_url: "https://api.github.com/users/karapeoples/repos",
		events_url: "https://api.github.com/users/karapeoples/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/karapeoples/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "JasonCruz-Dev",
		id: 54033391,
		node_id: "MDQ6VXNlcjU0MDMzMzkx",
		avatar_url: "https://avatars.githubusercontent.com/u/54033391?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/JasonCruz-Dev",
		html_url: "https://github.com/JasonCruz-Dev",
		followers_url: "https://api.github.com/users/JasonCruz-Dev/followers",
		following_url:
			"https://api.github.com/users/JasonCruz-Dev/following{/other_user}",
		gists_url: "https://api.github.com/users/JasonCruz-Dev/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/JasonCruz-Dev/starred{/owner}{/repo}",
		subscriptions_url:
			"https://api.github.com/users/JasonCruz-Dev/subscriptions",
		organizations_url: "https://api.github.com/users/JasonCruz-Dev/orgs",
		repos_url: "https://api.github.com/users/JasonCruz-Dev/repos",
		events_url: "https://api.github.com/users/JasonCruz-Dev/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/JasonCruz-Dev/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "RSibaja88",
		id: 54650378,
		node_id: "MDQ6VXNlcjU0NjUwMzc4",
		avatar_url: "https://avatars.githubusercontent.com/u/54650378?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/RSibaja88",
		html_url: "https://github.com/RSibaja88",
		followers_url: "https://api.github.com/users/RSibaja88/followers",
		following_url:
			"https://api.github.com/users/RSibaja88/following{/other_user}",
		gists_url: "https://api.github.com/users/RSibaja88/gists{/gist_id}",
		starred_url:
			"https://api.github.com/users/RSibaja88/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/RSibaja88/subscriptions",
		organizations_url: "https://api.github.com/users/RSibaja88/orgs",
		repos_url: "https://api.github.com/users/RSibaja88/repos",
		events_url: "https://api.github.com/users/RSibaja88/events{/privacy}",
		received_events_url:
			"https://api.github.com/users/RSibaja88/received_events",
		type: "User",
		site_admin: false,
	},
	{
		login: "aply333",
		id: 57161609,
		node_id: "MDQ6VXNlcjU3MTYxNjA5",
		avatar_url: "https://avatars.githubusercontent.com/u/57161609?v=4",
		gravatar_id: "",
		url: "https://api.github.com/users/aply333",
		html_url: "https://github.com/aply333",
		followers_url: "https://api.github.com/users/aply333/followers",
		following_url:
			"https://api.github.com/users/aply333/following{/other_user}",
		gists_url: "https://api.github.com/users/aply333/gists{/gist_id}",
		starred_url: "https://api.github.com/users/aply333/starred{/owner}{/repo}",
		subscriptions_url: "https://api.github.com/users/aply333/subscriptions",
		organizations_url: "https://api.github.com/users/aply333/orgs",
		repos_url: "https://api.github.com/users/aply333/repos",
		events_url: "https://api.github.com/users/aply333/events{/privacy}",
		received_events_url: "https://api.github.com/users/aply333/received_events",
		type: "User",
		site_admin: false,
	},
];
